-- Fleet Dispatcher — PostgreSQL schema
--
-- Source of truth for the ApiLogicServer (ALS) model. ALS reflects this schema
-- to generate SQLAlchemy models and the JSON:API; it relies on the FOREIGN KEY
-- constraints below to generate resource relationships, so every association
-- between domain objects is expressed as a real FK.
--
-- Design conventions (matching the Student-Onboarding / Smitty-Services apps):
--   * Lookup tables (driver_type, run_type, load_status, ...) use sequential
--     INTEGER identity keys; they hold the reference/enumeration data.
--   * Domain objects use auto-generated GUID (UUID) primary keys.
--   * Relationships between domain objects are enforced with FK constraints.
--
-- This PostgreSQL instance is shared with the Smitty-Services and
-- Student-Onboarding apps, so Fleet Dispatcher lives in its OWN schema (`fleet`)
-- rather than `public`. ALS reflects the `fleet` schema (its connection's
-- search_path includes it). Resource names are unchanged (they come from the
-- table names), so the portals/clients are unaffected.
--
-- Apply with:  psql "$DATABASE_URL" -f database/schema.sql
--   (run as the `fleet` role; see scripts/db-setup.sh / docs/DEPLOYMENT.md)

BEGIN;

-- All objects below land in the `fleet` schema.
CREATE SCHEMA IF NOT EXISTS fleet;
SET search_path TO fleet, public;

-- gen_random_uuid() is built into PostgreSQL 13+ (lives in pg_catalog).

-- ===========================================================================
-- Lookup tables  (sequential integer keys; reference data)
-- ===========================================================================

-- Contract type. default_percent carries the settlement share so the 30/70 rule
-- lives as data, not code (Company 30%, Owner-Operator 70%).
CREATE TABLE driver_type (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    default_percent SMALLINT NOT NULL CHECK (default_percent BETWEEN 0 AND 100),
    owner_bears_costs BOOLEAN NOT NULL  -- TRUE => owner/driver bears fuel/tolls/maint/repairs
);

CREATE TABLE run_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE load_status (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE power_unit (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE trailer_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE app_role (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE commodity_category (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

-- ===========================================================================
-- Identity & Access  (domain objects; UUID keys)
-- ===========================================================================
CREATE TABLE app_user (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username      TEXT NOT NULL UNIQUE,
    full_name     TEXT NOT NULL,
    email         TEXT,
    app_role_id   INTEGER NOT NULL REFERENCES app_role(id),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    -- Authentication: ApiLogicServer's built-in JWT auth verifies against this
    -- hash (format must match the ALS auth provider's hasher — see
    -- docs/AUTHENTICATION.md). Never store plaintext.
    password_hash TEXT,
    -- Profile fields (editable from the client profile screen).
    phone             TEXT,
    title             TEXT,                 -- job title, e.g. "Lead Dispatcher"
    timezone          TEXT,                 -- IANA tz, e.g. "America/Chicago"
    avatar_document_id UUID,                -- profile photo via the CMS document table (FK added below)
    last_login_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- Fleet context
-- ===========================================================================
CREATE TABLE driver (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name           TEXT NOT NULL,
    driver_type_id INTEGER NOT NULL REFERENCES driver_type(id),
    phone          TEXT,
    email          TEXT,
    home_base      TEXT,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    -- Optional link to a login (Driver role).
    user_id        UUID REFERENCES app_user(id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE equipment (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    unit_number     TEXT NOT NULL UNIQUE,
    power_unit_id   INTEGER NOT NULL REFERENCES power_unit(id),
    trailer_type_id INTEGER NOT NULL REFERENCES trailer_type(id),
    has_ramps       BOOLEAN NOT NULL DEFAULT FALSE,
    -- Trailer capacity (per tractor/trailer configuration) for multi-load route
    -- optimization: deck space (linear feet) + payload weight. Both dimensions.
    deck_length_ft  SMALLINT CHECK (deck_length_ft IS NULL OR deck_length_ft > 0),
    weight_capacity_lbs INTEGER CHECK (weight_capacity_lbs IS NULL OR weight_capacity_lbs > 0),
    has_duals       BOOLEAN NOT NULL DEFAULT FALSE,
    in_service      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Which equipment a driver is qualified/assigned to operate (association).
-- Surrogate UUID key + unique pair keeps it ALS/JSON:API-friendly.
CREATE TABLE driver_equipment (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id     UUID NOT NULL REFERENCES driver(id) ON DELETE CASCADE,
    equipment_id  UUID NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
    UNIQUE (driver_id, equipment_id)
);

-- ===========================================================================
-- Dispatch context
-- ===========================================================================
CREATE TABLE location (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    line1         TEXT NOT NULL,
    line2         TEXT,
    city          TEXT NOT NULL,
    state         TEXT NOT NULL,
    postal_code   TEXT NOT NULL,
    country       TEXT NOT NULL DEFAULT 'USA'
);

CREATE TABLE shipper (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          TEXT NOT NULL,
    location_id   UUID REFERENCES location(id),
    contact       TEXT
);

CREATE TABLE receiver (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          TEXT NOT NULL,
    location_id   UUID REFERENCES location(id),
    contact       TEXT
);

CREATE TABLE commodity (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    description           TEXT NOT NULL,
    commodity_category_id INTEGER NOT NULL REFERENCES commodity_category(id),
    weight_lbs            INTEGER CHECK (weight_lbs IS NULL OR weight_lbs >= 0)
);

-- A dispatch week, identified by its opening Monday (Monday -> Monday).
CREATE TABLE dispatch_week (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    week_start    DATE NOT NULL UNIQUE,   -- must be a Monday
    CONSTRAINT week_start_is_monday CHECK (EXTRACT(DOW FROM week_start) = 1)
);

CREATE TABLE load (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dispatch_week_id UUID NOT NULL REFERENCES dispatch_week(id),
    driver_id        UUID REFERENCES driver(id),
    equipment_id     UUID REFERENCES equipment(id),
    shipper_id       UUID NOT NULL REFERENCES shipper(id),
    receiver_id      UUID NOT NULL REFERENCES receiver(id),
    commodity_id     UUID NOT NULL REFERENCES commodity(id),
    pickup_id        UUID NOT NULL REFERENCES location(id),
    dropoff_id       UUID NOT NULL REFERENCES location(id),
    run_type_id      INTEGER NOT NULL REFERENCES run_type(id),
    load_status_id   INTEGER NOT NULL REFERENCES load_status(id),
    deadhead_miles   NUMERIC(8,1) NOT NULL DEFAULT 0 CHECK (deadhead_miles >= 0),
    loaded_miles     NUMERIC(8,1) NOT NULL DEFAULT 0 CHECK (loaded_miles >= 0),
    rate             NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (rate >= 0),  -- post-broker
    -- Load footprint for multi-load (shared-trailer) route optimization: linear
    -- deck feet + weight. Checked against equipment capacity by the optimizer.
    deck_feet        NUMERIC(5,1) CHECK (deck_feet IS NULL OR deck_feet >= 0),
    weight_lbs       INTEGER CHECK (weight_lbs IS NULL OR weight_lbs >= 0),
    currency         TEXT NOT NULL DEFAULT 'USD',
    -- Scheduling within the dispatch week: drives the desktop board's
    -- Today (pickup_date = today) vs Week (placed by pickup_date) views.
    pickup_date      DATE,
    delivery_date    DATE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT distinct_pickup_dropoff CHECK (pickup_id <> dropoff_id),
    CONSTRAINT delivery_after_pickup CHECK (
        delivery_date IS NULL OR pickup_date IS NULL OR delivery_date >= pickup_date
    )
);

CREATE INDEX idx_load_driver_week ON load (driver_id, dispatch_week_id);
CREATE INDEX idx_load_pickup_date ON load (pickup_date);

-- ===========================================================================
-- Settlement context
-- ===========================================================================
CREATE TABLE settlement (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id            UUID NOT NULL REFERENCES driver(id),
    load_id              UUID NOT NULL UNIQUE REFERENCES load(id),
    gross_rate           NUMERIC(12,2) NOT NULL CHECK (gross_rate >= 0),
    contract_percent     SMALLINT NOT NULL CHECK (contract_percent BETWEEN 0 AND 100),
    driver_pay           NUMERIC(12,2) NOT NULL CHECK (driver_pay >= 0),
    costs_borne_by_owner BOOLEAN NOT NULL,
    currency             TEXT NOT NULL DEFAULT 'USD',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- Messaging context  (message board: groups, direct messages; documents via CMS)
-- ===========================================================================

-- Lookup tables (sequential integer keys)
CREATE TABLE channel_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,    -- direct | group | broadcast
    name  TEXT NOT NULL
);

CREATE TABLE channel_member_role (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,    -- owner | member
    name  TEXT NOT NULL
);

-- Visibility scope a user chooses when pinning a message (see message_pin).
CREATE TABLE pin_scope (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,    -- self | channel | everyone
    name  TEXT NOT NULL
);

CREATE TABLE document_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,    -- document | image | bill_of_lading | invoice | inspection_photo | license | other
    name  TEXT NOT NULL
);

-- A conversation space: a group/board or a 1:1 direct thread. Participants are
-- app_users (drivers, dispatchers, updaters all unify here).
CREATE TABLE channel (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    channel_type_id INTEGER NOT NULL REFERENCES channel_type(id),
    created_by      UUID NOT NULL REFERENCES app_user(id),
    is_archived     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Membership of a user in a channel, with their read position.
CREATE TABLE channel_member (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    channel_id      UUID NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES app_user(id),
    member_role_id  INTEGER NOT NULL REFERENCES channel_member_role(id),
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_read_at    TIMESTAMPTZ,           -- for unread counts
    UNIQUE (channel_id, user_id)
);

-- A text message posted to a channel. reply_to_id supports threaded replies.
CREATE TABLE message (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    channel_id  UUID NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
    author_id   UUID NOT NULL REFERENCES app_user(id),
    reply_to_id UUID REFERENCES message(id),
    body        TEXT NOT NULL DEFAULT '',  -- may be empty when attachment-only
    posted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    edited_at   TIMESTAMPTZ
);

CREATE INDEX idx_message_channel_posted ON message (channel_id, posted_at);

-- A pinned message. The pinner chooses how widely the pin is visible via
-- pin_scope: 'self' (only the pinner), 'channel' (everyone in the channel), or
-- 'everyone' (org-wide). channel_id is carried here (= the message's channel) so
-- channel-scoped pins filter without a join. One pin per (message, user); a user
-- re-scopes by updating their row.
CREATE TABLE message_pin (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id    UUID NOT NULL REFERENCES message(id) ON DELETE CASCADE,
    channel_id    UUID NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
    pinned_by     UUID NOT NULL REFERENCES app_user(id),
    pin_scope_id  INTEGER NOT NULL REFERENCES pin_scope(id),
    pinned_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (message_id, pinned_by)
);

CREATE INDEX idx_message_pin_channel ON message_pin (channel_id);
CREATE INDEX idx_message_pin_message ON message_pin (message_id);

-- A user's personal saved/archive collection: any message, from any channel,
-- kept aside for later with an optional personal note. Distinct from channels
-- (organization) and from pins (shared importance) — this is per-user.
CREATE TABLE saved_message (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES app_user(id),
    message_id  UUID NOT NULL REFERENCES message(id) ON DELETE CASCADE,
    note        TEXT,                                   -- optional annotation
    saved_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, message_id)
);

CREATE INDEX idx_saved_message_user ON saved_message (user_id, saved_at);

-- ===========================================================================
-- Content (CMS) context
--
-- A document is a first-class, reusable content resource (digital scan, image,
-- BOL, invoice, artifact). The binary lives in the DB (bytea) with metadata
-- alongside. Documents are linked to other resources via FK join tables, so the
-- same document can be reached from messages, loads, and (later) inspections,
-- drivers, equipment, etc.
-- ===========================================================================
CREATE TABLE document (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title            TEXT NOT NULL,
    document_type_id INTEGER NOT NULL REFERENCES document_type(id),
    filename         TEXT NOT NULL,
    content_type     TEXT NOT NULL,             -- MIME type, e.g. image/jpeg
    byte_size        INTEGER NOT NULL CHECK (byte_size >= 0),
    checksum         TEXT,                      -- e.g. md5/sha256 hex
    data             BYTEA NOT NULL,            -- the artifact bytes
    uploaded_by      UUID NOT NULL REFERENCES app_user(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A user's profile photo is a CMS document (defined here, after `document`).
-- ALS reads this FK to relate AppUser -> Document for the avatar.
ALTER TABLE app_user
    ADD CONSTRAINT app_user_avatar_document_fk
    FOREIGN KEY (avatar_document_id) REFERENCES document(id);

-- Link tables (one per related resource): keep FK integrity and let ApiLogicServer
-- generate the relationships. Add load_document, driver_document, etc. as needed.
CREATE TABLE message_document (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id  UUID NOT NULL REFERENCES message(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    UNIQUE (message_id, document_id)
);

CREATE TABLE load_document (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    load_id     UUID NOT NULL REFERENCES load(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    UNIQUE (load_id, document_id)
);

CREATE INDEX idx_message_document_message ON message_document (message_id);
CREATE INDEX idx_load_document_load ON load_document (load_id);

-- ===========================================================================
-- Dispatcher HUD command channel
--
-- An append-only command/event stream so a remote HUD (separate process /
-- machine) can subscribe to control commands issued from the dispatcher
-- console (the same-server case uses an in-process Wt server-push bus instead).
-- command_type is free text (an event log, not reference data): e.g. set_mode,
-- focus_driver, highlight_load; arg carries the payload (e.g. "week").
-- ===========================================================================
CREATE TABLE hud_command (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    command_type TEXT NOT NULL,
    arg          TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_hud_command_created ON hud_command (created_at);

-- ===========================================================================
-- Telemetry context — truck locations  (ALS-facing, lat/lng numeric)
--
-- Realtime positions ingested from interchangeable sources (AirTags, Google
-- devices, driver phone push). Per the geospatial decision
-- (SPATIAL_GIS_DATA_CONSIDERATIONS.md) these ALS tables carry **plain lat/lng
-- numeric** columns — NO PostGIS geometry. Geometry/spatial queries live in a
-- separate `gis` schema + endpoint (added when PostGIS is configured).
-- ===========================================================================
CREATE TABLE location_source (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,   -- airtag | google_device | phone_push
    name  TEXT NOT NULL
);

CREATE TABLE position_report (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    equipment_id       UUID REFERENCES equipment(id),
    driver_id          UUID REFERENCES driver(id),
    location_source_id INTEGER NOT NULL REFERENCES location_source(id),
    lat                DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng                DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
    heading_deg        DOUBLE PRECISION CHECK (heading_deg IS NULL OR (heading_deg >= 0 AND heading_deg < 360)),
    speed_mph          DOUBLE PRECISION CHECK (speed_mph IS NULL OR speed_mph >= 0),
    accuracy_m         DOUBLE PRECISION CHECK (accuracy_m IS NULL OR accuracy_m >= 0),
    recorded_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A report identifies a rig and/or a driver.
    CONSTRAINT position_has_subject CHECK (equipment_id IS NOT NULL OR driver_id IS NOT NULL)
);

CREATE INDEX idx_position_report_equipment_time ON position_report (equipment_id, recorded_at DESC);
CREATE INDEX idx_position_report_recorded ON position_report (recorded_at);

-- ===========================================================================
-- Navigation context  (trips, waypoints, POIs/truck-stops, routes)
--
-- ALS-facing, lat/lng numeric. Truck-legal routing comes from HERE later (the
-- result is persisted as an encoded polyline TEXT on `route`); spatial queries
-- live in the separate `gis` schema/endpoint.
-- ===========================================================================
CREATE TABLE trip_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,   -- planned | active | completed | cancelled
    name TEXT NOT NULL
);

CREATE TABLE stop_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,   -- origin | destination | waypoint | fuel | rest | truck_stop | lunch | load_stop
    name TEXT NOT NULL
);

CREATE TABLE poi_category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,   -- fuel | rest_area | weigh_station | truck_stop | customer
    name TEXT NOT NULL
);

CREATE TABLE trip (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id      UUID REFERENCES driver(id),
    equipment_id   UUID REFERENCES equipment(id),
    load_id        UUID REFERENCES load(id),
    trip_status_id INTEGER NOT NULL REFERENCES trip_status(id),
    name           TEXT,
    started_at     TIMESTAMPTZ,
    ended_at       TIMESTAMPTZ,
    -- Set TRUE when a driver manually edits the stop order (add/remove/reorder).
    -- The route OPTIMIZER must not auto-reorder a locked trip; geometry recompute
    -- (which preserves order) still runs. Clear it to re-enable optimization.
    route_locked   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT trip_end_after_start CHECK (
        ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

CREATE INDEX idx_trip_driver ON trip (driver_id);

-- Ordered stops along a trip (origin → … → destination).
CREATE TABLE waypoint (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id         UUID NOT NULL REFERENCES trip(id) ON DELETE CASCADE,
    seq             INTEGER NOT NULL,
    stop_type_id    INTEGER NOT NULL REFERENCES stop_type(id),
    label           TEXT,
    lat             DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng             DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
    planned_arrival TIMESTAMPTZ,
    arrived_at      TIMESTAMPTZ,
    UNIQUE (trip_id, seq)
);

CREATE INDEX idx_waypoint_trip ON waypoint (trip_id, seq);

-- Reference points of interest (incl. truck stops via poi_category).
CREATE TABLE point_of_interest (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    poi_category_id INTEGER NOT NULL REFERENCES poi_category(id),
    lat             DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng             DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
    amenities       TEXT
);

-- A computed route (from HERE later); polyline kept as text (spatial-safe).
CREATE TABLE route (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id       UUID REFERENCES trip(id) ON DELETE CASCADE,
    origin_lat    DOUBLE PRECISION,
    origin_lng    DOUBLE PRECISION,
    dest_lat      DOUBLE PRECISION,
    dest_lng      DOUBLE PRECISION,
    polyline      TEXT,
    distance_mi   NUMERIC(8,1) CHECK (distance_mi IS NULL OR distance_mi >= 0),
    drive_minutes INTEGER CHECK (drive_minutes IS NULL OR drive_minutes >= 0),
    provider      TEXT NOT NULL DEFAULT 'here',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_route_trip ON route (trip_id);

-- Realtime change events are produced by ApiLogicServer (ALS events → Kafka),
-- not by DB triggers — see realtime/ (the WebSocket bridge consumes Kafka) and
-- docs/REALTIME.md. The DB stays the source of truth; the bridge is a stateless
-- fan-out and clients keep a slow reconcile poll as a fallback.

COMMIT;

-- Invariants for the middleware (LogicBank), enforced at the transaction boundary:
--   * load: at most 4 non-cancelled loads per (driver_id, dispatch_week_id).
--   * settlement.contract_percent  <- driver.driver_type.default_percent
--   * settlement.costs_borne_by_owner <- driver.driver_type.owner_bears_costs
--   * settlement.driver_pay = round(gross_rate * contract_percent / 100, 2)
--   * equipment/commodity compatibility on load assignment.
--   * channel_member.last_read_at drives per-user unread message counts.
--   * document.byte_size / checksum should match data on upload.
