-- Fleet Dispatcher — PostgreSQL schema
--
-- Source of truth for the ApiLogicServer (ALS) model. ALS reflects this schema
-- to generate SQLAlchemy models and the JSON:API; it relies on the FOREIGN KEY
-- constraints below to generate resource relationships, so every association
-- between domain objects is expressed as a real FK.
--
-- Design conventions (matching the Student-Onboarding / Smitty-Services apps):
--   * Lookup tables (driver_type, run_type, load_status, ...) use sequential
--     INTEGER identity keys; they hold the reference/enumeration data.
--   * Domain objects use auto-generated GUID (UUID) primary keys.
--   * Relationships between domain objects are enforced with FK constraints.
--
-- Apply with:  psql "$DATABASE_URL" -f database/schema.sql

BEGIN;

-- gen_random_uuid() is built into PostgreSQL 13+. (Enable pgcrypto on older.)
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===========================================================================
-- Lookup tables  (sequential integer keys; reference data)
-- ===========================================================================

-- Contract type. default_percent carries the settlement share so the 30/70 rule
-- lives as data, not code (Company 30%, Owner-Operator 70%).
CREATE TABLE driver_type (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    default_percent SMALLINT NOT NULL CHECK (default_percent BETWEEN 0 AND 100),
    owner_bears_costs BOOLEAN NOT NULL  -- TRUE => owner/driver bears fuel/tolls/maint/repairs
);

CREATE TABLE run_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE load_status (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE power_unit (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE trailer_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE app_role (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

CREATE TABLE commodity_category (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,
    name  TEXT NOT NULL
);

-- ===========================================================================
-- Identity & Access  (domain objects; UUID keys)
-- ===========================================================================
CREATE TABLE app_user (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username      TEXT NOT NULL UNIQUE,
    full_name     TEXT NOT NULL,
    email         TEXT,
    app_role_id   INTEGER NOT NULL REFERENCES app_role(id),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- Fleet context
-- ===========================================================================
CREATE TABLE driver (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name           TEXT NOT NULL,
    driver_type_id INTEGER NOT NULL REFERENCES driver_type(id),
    phone          TEXT,
    email          TEXT,
    home_base      TEXT,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    -- Optional link to a login (Driver role).
    user_id        UUID REFERENCES app_user(id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE equipment (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    unit_number     TEXT NOT NULL UNIQUE,
    power_unit_id   INTEGER NOT NULL REFERENCES power_unit(id),
    trailer_type_id INTEGER NOT NULL REFERENCES trailer_type(id),
    has_ramps       BOOLEAN NOT NULL DEFAULT FALSE,
    deck_length_ft  SMALLINT CHECK (deck_length_ft IS NULL OR deck_length_ft > 0),
    has_duals       BOOLEAN NOT NULL DEFAULT FALSE,
    in_service      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Which equipment a driver is qualified/assigned to operate (association).
-- Surrogate UUID key + unique pair keeps it ALS/JSON:API-friendly.
CREATE TABLE driver_equipment (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id     UUID NOT NULL REFERENCES driver(id) ON DELETE CASCADE,
    equipment_id  UUID NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
    UNIQUE (driver_id, equipment_id)
);

-- ===========================================================================
-- Dispatch context
-- ===========================================================================
CREATE TABLE location (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    line1         TEXT NOT NULL,
    line2         TEXT,
    city          TEXT NOT NULL,
    state         TEXT NOT NULL,
    postal_code   TEXT NOT NULL,
    country       TEXT NOT NULL DEFAULT 'USA'
);

CREATE TABLE shipper (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          TEXT NOT NULL,
    location_id   UUID REFERENCES location(id),
    contact       TEXT
);

CREATE TABLE receiver (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          TEXT NOT NULL,
    location_id   UUID REFERENCES location(id),
    contact       TEXT
);

CREATE TABLE commodity (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    description           TEXT NOT NULL,
    commodity_category_id INTEGER NOT NULL REFERENCES commodity_category(id),
    weight_lbs            INTEGER CHECK (weight_lbs IS NULL OR weight_lbs >= 0)
);

-- A dispatch week, identified by its opening Monday (Monday -> Monday).
CREATE TABLE dispatch_week (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    week_start    DATE NOT NULL UNIQUE,   -- must be a Monday
    CONSTRAINT week_start_is_monday CHECK (EXTRACT(DOW FROM week_start) = 1)
);

CREATE TABLE load (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dispatch_week_id UUID NOT NULL REFERENCES dispatch_week(id),
    driver_id        UUID REFERENCES driver(id),
    equipment_id     UUID REFERENCES equipment(id),
    shipper_id       UUID NOT NULL REFERENCES shipper(id),
    receiver_id      UUID NOT NULL REFERENCES receiver(id),
    commodity_id     UUID NOT NULL REFERENCES commodity(id),
    pickup_id        UUID NOT NULL REFERENCES location(id),
    dropoff_id       UUID NOT NULL REFERENCES location(id),
    run_type_id      INTEGER NOT NULL REFERENCES run_type(id),
    load_status_id   INTEGER NOT NULL REFERENCES load_status(id),
    deadhead_miles   NUMERIC(8,1) NOT NULL DEFAULT 0 CHECK (deadhead_miles >= 0),
    loaded_miles     NUMERIC(8,1) NOT NULL DEFAULT 0 CHECK (loaded_miles >= 0),
    rate             NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (rate >= 0),  -- post-broker
    currency         TEXT NOT NULL DEFAULT 'USD',
    -- Scheduling within the dispatch week: drives the desktop board's
    -- Today (pickup_date = today) vs Week (placed by pickup_date) views.
    pickup_date      DATE,
    delivery_date    DATE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT distinct_pickup_dropoff CHECK (pickup_id <> dropoff_id),
    CONSTRAINT delivery_after_pickup CHECK (
        delivery_date IS NULL OR pickup_date IS NULL OR delivery_date >= pickup_date
    )
);

CREATE INDEX idx_load_driver_week ON load (driver_id, dispatch_week_id);
CREATE INDEX idx_load_pickup_date ON load (pickup_date);

-- ===========================================================================
-- Settlement context
-- ===========================================================================
CREATE TABLE settlement (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id            UUID NOT NULL REFERENCES driver(id),
    load_id              UUID NOT NULL UNIQUE REFERENCES load(id),
    gross_rate           NUMERIC(12,2) NOT NULL CHECK (gross_rate >= 0),
    contract_percent     SMALLINT NOT NULL CHECK (contract_percent BETWEEN 0 AND 100),
    driver_pay           NUMERIC(12,2) NOT NULL CHECK (driver_pay >= 0),
    costs_borne_by_owner BOOLEAN NOT NULL,
    currency             TEXT NOT NULL DEFAULT 'USD',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- Messaging context  (message board: groups, direct messages; documents via CMS)
-- ===========================================================================

-- Lookup tables (sequential integer keys)
CREATE TABLE channel_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,    -- direct | group | broadcast
    name  TEXT NOT NULL
);

CREATE TABLE channel_member_role (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,    -- owner | member
    name  TEXT NOT NULL
);

CREATE TABLE document_type (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  TEXT NOT NULL UNIQUE,    -- document | image | bill_of_lading | invoice | inspection_photo | license | other
    name  TEXT NOT NULL
);

-- A conversation space: a group/board or a 1:1 direct thread. Participants are
-- app_users (drivers, dispatchers, updaters all unify here).
CREATE TABLE channel (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    channel_type_id INTEGER NOT NULL REFERENCES channel_type(id),
    created_by      UUID NOT NULL REFERENCES app_user(id),
    is_archived     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Membership of a user in a channel, with their read position.
CREATE TABLE channel_member (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    channel_id      UUID NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES app_user(id),
    member_role_id  INTEGER NOT NULL REFERENCES channel_member_role(id),
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_read_at    TIMESTAMPTZ,           -- for unread counts
    UNIQUE (channel_id, user_id)
);

-- A text message posted to a channel. reply_to_id supports threaded replies.
CREATE TABLE message (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    channel_id  UUID NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
    author_id   UUID NOT NULL REFERENCES app_user(id),
    reply_to_id UUID REFERENCES message(id),
    body        TEXT NOT NULL DEFAULT '',  -- may be empty when attachment-only
    posted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    edited_at   TIMESTAMPTZ
);

CREATE INDEX idx_message_channel_posted ON message (channel_id, posted_at);

-- ===========================================================================
-- Content (CMS) context
--
-- A document is a first-class, reusable content resource (digital scan, image,
-- BOL, invoice, artifact). The binary lives in the DB (bytea) with metadata
-- alongside. Documents are linked to other resources via FK join tables, so the
-- same document can be reached from messages, loads, and (later) inspections,
-- drivers, equipment, etc.
-- ===========================================================================
CREATE TABLE document (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title            TEXT NOT NULL,
    document_type_id INTEGER NOT NULL REFERENCES document_type(id),
    filename         TEXT NOT NULL,
    content_type     TEXT NOT NULL,             -- MIME type, e.g. image/jpeg
    byte_size        INTEGER NOT NULL CHECK (byte_size >= 0),
    checksum         TEXT,                      -- e.g. md5/sha256 hex
    data             BYTEA NOT NULL,            -- the artifact bytes
    uploaded_by      UUID NOT NULL REFERENCES app_user(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Link tables (one per related resource): keep FK integrity and let ApiLogicServer
-- generate the relationships. Add load_document, driver_document, etc. as needed.
CREATE TABLE message_document (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id  UUID NOT NULL REFERENCES message(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    UNIQUE (message_id, document_id)
);

CREATE TABLE load_document (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    load_id     UUID NOT NULL REFERENCES load(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    UNIQUE (load_id, document_id)
);

CREATE INDEX idx_message_document_message ON message_document (message_id);
CREATE INDEX idx_load_document_load ON load_document (load_id);

-- ===========================================================================
-- Dispatcher HUD command channel
--
-- An append-only command/event stream so a remote HUD (separate process /
-- machine) can subscribe to control commands issued from the dispatcher
-- console (the same-server case uses an in-process Wt server-push bus instead).
-- command_type is free text (an event log, not reference data): e.g. set_mode,
-- focus_driver, highlight_load; arg carries the payload (e.g. "week").
-- ===========================================================================
CREATE TABLE hud_command (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    command_type TEXT NOT NULL,
    arg          TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_hud_command_created ON hud_command (created_at);

COMMIT;

-- Invariants for the middleware (LogicBank), enforced at the transaction boundary:
--   * load: at most 4 non-cancelled loads per (driver_id, dispatch_week_id).
--   * settlement.contract_percent  <- driver.driver_type.default_percent
--   * settlement.costs_borne_by_owner <- driver.driver_type.owner_bears_costs
--   * settlement.driver_pay = round(gross_rate * contract_percent / 100, 2)
--   * equipment/commodity compatibility on load assignment.
--   * channel_member.last_read_at drives per-user unread message counts.
--   * document.byte_size / checksum should match data on upload.
